name: Build application

on:
  workflow_dispatch:

  pull_request:
  push:
    branches:
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.6"
      - name: Install tools
        run: make tool
      - name: Lint code
        run: make lint
      - name: Run tests
        run: make test
      - name: Build project
        run: make build
